### PR TITLE
Added animation scrolling

### PR DESCRIPTION
**Pull request by Ribster**
Hey @hubmartin , i added some animation scrolling.
The bar goes left / right or left/right.
Press 'd' to change modus.
Let me know what you think

### CODE REVIEW

**Comment by hubmartin** [comment]
Hi @Ribster,
that's nice improvement. I take a look at it few days later during holidays.
Your idea is basicaly a "filter" which can be applied to any effect. I have to rethink how to improve implementation of effects and filters.
What I would like to avoid is changing device.positionOffset.x at all. This offset is there that you can chain multiple LED strips od different Network devices. But now it is completely ok, I'm more thinking about the future.
Also I'm still learning GIT. It takes me 20 minutes to learn how to test your pull request and just 2 minutes to actually test it and push it :(
I'll be back in a few days.

**Comment by Ribster** [comment]
Hehe, no problem. 
Git is a learning experience for everybody. 
I think this is the most elegant way for me to add my changes to your repo.
I understand you want to keep the led strips position at the same location. 
But this was the fastest way to add a cool effect.
This way, the programming gets easier because they are 2 separate routines..
Take your time!

**Comment by hubmartin** [comment]
Hi @Ribster,
I've completely rebuild the way the effects are managed. Now it's all in data/config.xml and I added first example of sound effect.
Right now I'm unable to merge your code but thanks to your idea of applying more effects togeher I would add this option to the XML config soon.

It would look like this concept:
```
<effects>
        <effect name="dotsMoving">
                <effect name="dots" mode="color" />
                <effect name="shiftView" speed="10" />
        </effect>

        <effect name="soundLevel" />
        <effect name="plasma" />
    </effects>

```
Let me know what you think.

Happy new year,
best, 
Martin

**Comment by Ribster** [comment]
Hey man, i tested them out and it works great.
I like the idea of adding effects on the fly.

I am using OS X as my dev platform and i only can select the input audio.
It's related to minim i assume. But it would be cool to play the audio from the device and then get the VU meter also. (I could be wrong, i haven't tried it on a rasbpi, but soon.)

I'll look into a color gradient for the audio VU meter, because the led strip draws a little bit too much current for my taste.
It would be cool to have some effects together with the VU meter.

I think this is a powerfull platform for future development.
I'll keep you updated with new additions if any.

Happy new year.
Enjoy!

**Comment by hubmartin** [comment]
Thanks for the feedback.

**Comment by hubmartin** [comment]
It seems that it needs to select "Stereo Mix" as an input, it is not easy on Windows but I finally set it. I'm not familiar wit macOS, hope it will be possible.
http://www.howtogeek.com/217348/how-to-record-the-sound-coming-from-your-pc-even-without-stereo-mix/

**Comment by Ribster** [comment]
Yeah, stereomix is not available on macOS. 
There is always a solution.
Maybe a fake recording device that mirrors the output stream....

**Pull request closed without merging**
